keys:
  - &nix_key age100gp73gds90uts07ylq425nmq2gc2jdxnmy4f20uqmemrchds5nqsnw4f4
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *nix_key
