services:
  unifi:
    image: lscr.io/linuxserver/unifi-controller:latest
    container_name: unifi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /mnt/appdata/unifi/unifi/config/:/config/
    restart: always
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp
      - 8843:8843
      - 8880:8880
      - 6789:6789
      - 5514:5514/udp
    healthcheck:
      test: ["CMD", "curl", "-sSf", "localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
