services:
  podgrab:
    image: akhilrex/podgrab
    container_name: podgrab
    environment:
      - PUID=1000
      - PGID=1000
      - CHECK_FREQUENCY=240
    volumes:
      - /mnt/appdata/podgrab/podgrab/config/:/config/
      - /mnt/media/audio/podcasts/:/assets/
    restart: unless-stopped
    depends_on:
      - ts
    network_mode: "service:ts"
    healthcheck:
      test: ["CMD", "wget", "localhost:8080", "-O", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ts:
    hostname: podgrab
    image: tailscale/tailscale:latest
    volumes:
      - /mnt/appdata/podgrab/tailscale/var/lib/:/var/lib/
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    command: tailscaled
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "tailscale", "status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
