version: "3.7"
services:
  heimdall:
    image: linuxserver/heimdall:2.4.15
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /mnt/appdata/heimdall/heimdall/config/:/config/
    restart: on-failure
    depends_on:
      - ts
    network_mode: 'service:ts'
    healthcheck:
      test: ["CMD", "wget", "localhost", "-O", "/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  ts:
    hostname: heimdall
    image: tailscale/tailscale:latest
    volumes:
      - /mnt/appdata/heimdall/tailscale/var/lib/:/var/lib/
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    command: tailscaled
    restart: on-failure
    healthcheck:
      test: ["CMD", "tailscale", "ping", "alfred"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
